---
abstract: 'enable all of the features of Modern Perl with one import'
author:
  - chromatic
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Modern-Perl
requires:
  IO::File: '0'
  IO::Handle: '0'
  feature: '0'
  mro: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/chromatic/Modern-Perl
  repository: https://github.com/chromatic/Modern-Perl.git
version: '1.20200211'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
